FROM node:14.17 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

RUN npm i && npm run build

FROM nginx:alpine

COPY ./docker/nginx /etc/nginx/conf.d

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/public /usr/share/nginx/html

COPY ./docker/public /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
